extends: "@commitlint/config-conventional"

scopes: &scopes
  - actions
  - ci
  - editorconfig
  - git
  - lefthook
  - templates

rules:
  scope-empty: [2, never]
  scope-enum: [2, always, *scopes]
