pre-commit:
  piped: true
  commands:
    lint-files-with-editorconfig:
      priority: 1
      run: npx --yes editorconfig-checker {staged_files}
      tags: lint editorconfig

    lint-markdown-files:
      priority: 2
      glob: "*.md"
      run: npx --yes markdownlint-cli {staged_files}
      tags: lint markdownlint

commit-msg:
  commands:
    lint-commit-message:
      run: npx --yes commitlint --edit
      tags: lint commitlint
