pre-commit:
  piped: true
  commands:
    1-lint-files-with-editorconfig:
      run: npx --yes editorconfig-checker {staged_files}
      tags: lint editorconfig

    2-lint-markdown-files:
      glob: "*.md"
      run: npx --yes markdownlint-cli {staged_files}
      tags: lint markdownlint

commit-msg:
  commands:
    lint-commit-message:
      run: npx --yes commitlint --edit
      tags: lint commitlint
