pre-commit:
  piped: true
  jobs:
    - name: Lint files with EditorConfig
      run: npx --yes editorconfig-checker {staged_files}
      tags:
        - lint
        - editorconfig
    - name: Lint Markdown files
      glob: "*.md"
      run: npx --yes markdownlint-cli {staged_files}
      tags:
        - lint
        - markdownlint

commit-msg:
  jobs:
    - name: Lint commit message
      run: npx --yes commitlint --edit
      tags:
        - lint
        - commitlint
