output: [failure, meta, skips, success]

pre-commit:
  piped: true
  jobs:
    - name: Lint the files against EditorConfig
      run: editorconfig-checker {staged_files}
      tags:
        - lint
        - files
    - name: Lint Markdown files
      glob: "*.md"
      run: markdownlint-cli {staged_files}
      tags:
        - lint
        - files
        - markdown

commit-msg:
  jobs:
    - name: Lint the commit message
      run: commitlint --edit
      tags:
        - lint
        - commit
