name: Changed files linting

on:
  workflow_call:
    inputs:
      ls_command:
        type: string
        required: true
        description: Command used to list the changed files, e.g., a Git command.
      ref:
        type: string
        required: true
        description: The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.

jobs:
  lint-changed-files:
    name: Changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Retrieve changed files
        id: changed_files
        run: |
          echo "Retrieving changed files"
          CHANGED_FILES="${{ inputs.ls_command }}"
          FILES_COUNT=$(eval $CHANGED_FILES | wc -l | sed -e "s/^[[:space:]]*//")
          echo "files=$(echo $(eval $CHANGED_FILES))" >> $GITHUB_OUTPUT
          echo "files_count=$FILES_COUNT" >> $GITHUB_OUTPUT
          CHANGED_MARKDOWN_FILES="eval $CHANGED_FILES | { grep -E '.*\.(md|markdown)$' || true; }"
          MARKDOWN_FILES_COUNT=$(eval $CHANGED_MARKDOWN_FILES | wc -l | sed -e "s/^[[:space:]]*//")
          echo "markdown_files<<EOF" >> $GITHUB_OUTPUT
          echo "$(eval $CHANGED_MARKDOWN_FILES)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "markdown_files_count=$MARKDOWN_FILES_COUNT" >> $GITHUB_OUTPUT
          echo "::group::Changed files"
          echo "Total: $FILES_COUNT"
          echo "Markdown: $MARKDOWN_FILES_COUNT"
          echo "::endgroup::"
          eval $CHANGED_FILES
      - name: Setup a Node.js environment
        if: steps.changed_files.outputs.files_count > 0
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Lint changed files with EditorConfig-Checker
        if: steps.changed_files.outputs.files_count > 0
        run: npx editorconfig-checker ${{ steps.changed_files.outputs.files }}
    outputs:
      markdown_files: ${{ steps.changed_files.outputs.markdown_files }}
      markdown_files_count: ${{ steps.changed_files.outputs.markdown_files_count }}

  lint-markdown-files:
    name: Markdown files
    needs: lint-changed-files
    if: needs.lint-changed-files.outputs.markdown_files_count > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Lint changed Markdown files with markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: ${{ needs.lint-changed-files.outputs.markdown_files }}
