name: Commit messages linting

on:
  workflow_call:
    inputs:
      from:
        type: string
        required: false
        description: Reference of the first commit to lint
      to:
        type: string
        required: true
        description: Reference of the last commit to lint

jobs:
  lint-commit-messages:
    name: Commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.to }}
      - name: Setup a Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Lint commit messages
        run: |
          npm install --global @commitlint/config-conventional
          echo "::notice title=Last commit message::$(git show -s --format=%s)"
          npx commitlint${{ inputs.from && format(' --from {0}', inputs.from) }} --to ${{ inputs.to }}
