name: Files changed linting

on:
  workflow_call:
    inputs:
      ls_command:
        type: string
        required: true
        description: Command used to list the files changed, e.g., a Git command.
      ref:
        type: string
        required: true
        description: The branch, tag or SHA to checkout.

jobs:
  lint-files-against-editorconfig:
    name: Files compliance with EditorConfig
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Retrieve the files changed
        id: files_changed
        run: |
          echo "Retrieving the files changed..."
          files_changed="${{ inputs.ls_command }}"
          files_count=$(eval $files_changed | wc -l | sed -e "s/^[[:space:]]*//")
          echo "files=$(echo $(eval $files_changed))" >> $GITHUB_OUTPUT
          echo "files_count=$files_count" >> $GITHUB_OUTPUT
          markdown_files_changed="eval $files_changed | { grep -E '.*\.(md|markdown)$' || true; }"
          markdown_files_count=$(eval $markdown_files_changed | wc -l | sed -e "s/^[[:space:]]*//")
          echo "markdown_files<<EOF" >> $GITHUB_OUTPUT
          echo "$(eval $markdown_files_changed)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "markdown_files_count=$markdown_files_count" >> $GITHUB_OUTPUT
          echo "::group::Files changed"
          echo "Total: $files_count"
          echo "Markdown: $markdown_files_count"
          echo "::endgroup::"
          eval $files_changed
      - name: Setup a Node.js environment
        if: steps.files_changed.outputs.files_count > 0
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Lint the files against EditorConfig
        if: steps.files_changed.outputs.files_count > 0
        run: npx editorconfig-checker ${{ steps.files_changed.outputs.files }}
    outputs:
      markdown_files: ${{ steps.files_changed.outputs.markdown_files }}
      markdown_files_count: ${{ steps.files_changed.outputs.markdown_files_count }}

  lint-markdown-files:
    name: Markdown files
    needs: lint-files-against-editorconfig
    if: needs.lint-files-against-editorconfig.outputs.markdown_files_count > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Setup a Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Lint Markdown files
        run: npx markdownlint-cli ${{ needs.lint-files-against-editorconfig.outputs.markdown_files }}
