name: Integration validation
run-name: Validate integration to ${{ github.ref_name }} branch

on:
  push:
    branches: [main]

jobs:
  lint-commit-messages:
    name: Lint
    uses: ./.github/workflows/commit-messages-linting.yml
    with:
      to: ${{ github.sha }}

  lint-files-against-editorconfig:
    name: Lint
    needs: lint-commit-messages
    uses: ./.github/workflows/files-changed-linting.yml
    with:
      ls_command: git log -1 --diff-filter=ACMUX --first-parent --name-only --pretty="format:"
      ref: ${{ github.sha }}
